---
- include: setup.yml

- name: Configure Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: "{{ elasticsearch_install_dir }}elasticsearch/config/elasticsearch.yml"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: 0750
    backup: yes
  notify: restart elasticsearch

- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Wait for Elasticsearch
  wait_for:
    host: "{{ elasticsearch_network_host }}"
    port: "{{ elasticsearch_http_port }}"
    delay: 3
    timeout: 300