---

- name: Create elasticsearch group
  group:
    name: "{{ elasticsearch_group }}"
    state: present

- name: Create elasticsearch user
  user:
    name: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    createhome: yes
    state: present

- name: Download Elasticsearch archive
  unarchive:
    src: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}.tar.gz"
    remote_src: yes
    dest: "{{ elasticsearch_install_dir }}"
    group: "{{ elasticsearch_group }}"
    owner: "{{ elasticsearch_user }}"

- name: Create symbolic link
  file:
    src: "{{ elasticsearch_install_dir }}elasticsearch-{{ elasticsearch_version }}"
    dest: "{{ elasticsearch_install_dir }}elasticsearch"
    state: link

- name: Create default file
  template:
    src: ../templates/elasticsearch.environment
    dest: /etc/default/elasticsearch

- name: Create init script
  become: yes
  template:
    src: ../templates/init.Debian
    dest: /etc/init.d/elasticsearch
    mode: 0755

- name: Create service file
  become: yes
  template:
    src: ../templates/elasticsearch.service
    dest: /lib/systemd/system/elasticsearch.service
    mode: 0750

- name: Create log directory
  become: yes
  file:
    path: "{{ elasticsearch_log_dir }}"
    state: directory

- name: Create run directory
  become: yes
  file:
    path: /var/run/elasticsearch
    state: directory

- name: Update systemd
  become: yes
  systemd:
    name: elasticsearch
    daemon_reload: yes

#- name: Add Elasticsearch apt key.
#  apt_key:
#    url: https://packages.elastic.co/GPG-KEY-elasticsearch
#    state: present
#
#- name: Add Elasticsearch repository.
#  apt_repository:
#    repo: 'deb http://packages.elastic.co/elasticsearch/2.x/debian stable main'
#    state: present
#    update_cache: yes
#
#- name: Install Elasticsearch.
#  apt: pkg=elasticsearch state=present
